# Generated by Django 3.2.7 on 2021-09-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='caste',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='program',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, default='NA', max_length=255, null=True),
        ),
    ]
