# Generated by Django 3.2.7 on 2021-09-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='current_authority',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='receiver_authority_id',
        ),
    ]
